"""empty message

Revision ID: bdac7d621f42
Revises: 6a70552c2945
Create Date: 2023-08-23 17:19:16.639756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdac7d621f42'
down_revision = '6a70552c2945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['use_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('use_id')

    # ### end Alembic commands ###
